#!/bin/zsh
# Regenerate lab-slides.bundle.js from the ES-module sources.
#
# The deck framework is authored as ES modules (lab-slides.js + four .mjs
# files). Chrome refuses to load <script type="module"> over the file://
# scheme, so a deck opened by double-clicking shows a blank page. This bundle
# is the same code concatenated into one classic <script> (no import/export)
# wrapped in a strict IIFE, so decks render from file:// and http:// alike.
#
# Sources stay the source of truth. Re-run this after editing any of them.
set -e
dir="$1"                       # e.g. ism3232/assets
out="$dir/lab-slides.bundle.js"
{
  echo "// GENERATED by assets/build-bundle.sh from the ES-module sources."
  echo "// Do not edit by hand. Edit lab-shell.mjs / lab-pyodide.mjs /"
  echo "// lab-widgets.mjs / lab-draw.mjs / lab-slides.js and re-run the script."
  echo "(function(){"
  echo '"use strict";'
  for f in lab-shell.mjs lab-pyodide.mjs lab-widgets.mjs lab-draw.mjs lab-slides.js; do
    echo ""
    echo "// ===== $f ====="
    # strip the module boundary: `export [async] function` -> `[async] function`
    # (never appears inside the Python template literals), and drop lab-slides.js's
    # four `import { ... } from './x.mjs';` lines.
    sed -E \
      -e 's/^export (async )?function /\1function /' \
      -e "/^import \{[^}]*\} from '\.\/[a-z-]+\.mjs';$/d" \
      "$dir/$f"
  done
  echo ""
  echo "})();"
} > "$out"
node --check "$out" && echo "OK  $out  ($(wc -l < "$out") lines)"
